cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

language: java

jdk:
  - oraclejdk8
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent verify package sonar:sonar -Dsonar.organization=nilshoffmann-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
